export default {
  yellowSport: {
    name: "Yellow sport",
    imageLocation: "./images/cars/yellow_sport.png",
    height: 14,
    width: 25,
    maxPower: 5,
    acceleration: 1,
    braking: 0.25,
    handling: 10,
    handbrake: 2,
  },
  greenSport: {
    name: "Green sport",
    imageLocation: "./images/cars/green_sport.png",
    height: 14,
    width: 25,
    maxPower: 5,
    acceleration: 1,
    braking: 0.25,
    handling: 10,
    handbrake: 2,
  },
  rocket: {
    name: "Rocket",
    imageLocation: "./images/cars/rocket.png",
    height: 14,
    width: 25,
    maxPower: 10,
    acceleration: 1.5,
    braking: 0.25,
    handling: 10,
    handbrake: 2,
  },
};
